name: Deploy to DockerHub and GitHub Pages

on:
  push:
    branches:
      - master
      - feature

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint HTML
        uses: Cyb3r-Jak3/html5validator-action@v1.0.4

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-html
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest .

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - uses: actions/checkout@v2
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:${{ github.ref_name }}-latest

  github-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - uses: actions/checkout@v2
      - name: Upload page content
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
